java.home=${JAVA_HOME}
spring.application.name=delo-zhivet-task-tracker
server.address=0.0.0.0
server.port=${SERVER_PORT:9966}
server.servlet.session.timeout=${SESSION_TIMEOUT:72h}
server.servlet.context-path=${SERVLET_CONTEXT_PATH:}
springdoc.api-docs.path=${API_DOCS_PATH:/docs}
spring.servlet.multipart.max-file-size=${UPLOAD_MAX_FILE_SIZE:10MB}
spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=${STATIC_CONTENT_LOCATIONS:file:./.images/}
datasource.url=${PG_URL:jdbc:postgresql://host.docker.internal:5432/tracker}
datasource.username=${PG_USERNAME:site}
datasource.password=${PG_PASSWORD:1234}
credentials.bot.auth.token=${BOT_BACKEND_SECRET:kitty}
credentials.backend.auth.token=${BACKEND_BOT_SECRET:kitty}
credentials.user.auth.code.lifetime=${SERVER_AUTH_CODE_LIFETIME:300}
bot.uri=${BOT_URI:http://bot:9967/sendAuthCode}
images.rootLocation=${IMAGES_ROOT_LOCATION:./.images}
images.optimizedPhotoPrefix=optimized_
