spring:
  application:
    name: delo_zhivet
  mvc:
    async:
      request-timeout: 300000
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/tracker
    username: site
    password: ${PG_PASSWORD}

server:
  port: 9967
  address: 0.0.0.0

telegram:
  bot:
    username: DeloZhivetDevBot
    token: ${TELEGRAM_BOT_TOKEN}

dadata:
  client:
    token: ${DADATA_CLIENT_TOKEN}

springdoc:
  api-docs:
    path: /docs

app:
  project:
    name: Дело Живет
  backend:
    url: http://backend:9966
    token: ${APP_BACKEND_TOKEN:kitty}
